# Task file: install_jet.yml 

- !echo 
  msg: "Install Jet"

- !directory 
  path: ~/.pkg/jet 

- !directory 
  path: ~/.jetbin 

- !copy 
  src: ~/util/y-jet/scripts/js_geturl 
  dest: ~/.jetbin/js_geturl 

- !shell 
  cmd: TBD

